name: Report

on:
  pull_request:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.DVC_GCP_SERVICE_ACCOUNT_KEY }}'
      - name: Create CML report
        run: |
          # Compare metrics to main
          git fetch --depth=1 origin main:main

          # Add title to the report
          echo "# Experiment Report (${{ github.sha }})" >> report.md

          # Compare parameters to main branch
          echo "## Params workflow vs. main" >> report.md
          dvc params diff main --md >> report.md

          # Compare metrics to main branch
          echo "## Metrics workflow vs. main" >> report.md
          dvc metrics diff main --md >> report.md

          # Publish the CML report
          cml comment update --target=pr --publish report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
